
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  timeout: 5000
  username: rvvergara
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: help_development
test:
  <<: *default
  database: help_test
production:
  <<: *default
  database: help_production
  username: help
  password: <%= ENV['HELP_DATABASE_PASSWORD'] %>
